### ISSUE TITLE
textures

### ISSUE THREAD

**Issue by mixerrules** [Gnomorian/piggalot-mod#14]
here are the bacon and bow textures
![pigtite_bow](https://cloud.githubusercontent.com/assets/9809371/6051811/0e08043a-ac91-11e4-866d-f9596f56eb18.png)

![rawbacon](https://cloud.githubusercontent.com/assets/9809371/6051796/eea028de-ac90-11e4-8572-517853f927ff.png)

**Comment by Gnomorian** [comment]
added
